import { getScriptPropertyValue } from "../../common/src/spreadsheet";

export const SCRIPT_PROPERTIES = {
  MODE: "MODE",

  OCR_FOLDER_ID: "OCR_FOLDER_ID",
  DONE_OCR_FOLDER_ID: "DONE_OCR_FOLDER_ID",
  ERROR_OCR_FOLDER_ID: "ERROR_OCR_FOLDER_ID",
  CLOUD_VISION_API_KEY: "CLOUD_VISION_API_KEY",
  OPEN_AI_API_KEY: "OPEN_AI_API_KEY",
  OPEN_AI_MODEL: "OPEN_AI_MODEL",

  // 本番用
  OCR_FOLDER_ID_PROD: "OCR_FOLDER_ID_PROD",
  DONE_OCR_FOLDER_ID_PROD: "DONE_OCR_FOLDER_ID_PROD",
  ERROR_OCR_FOLDER_ID_PROD: "ERROR_OCR_FOLDER_ID_PROD",
  CLOUD_VISION_API_KEY_PROD: "CLOUD_VISION_API_KEY_PROD",
  OPEN_AI_API_KEY_PROD: "OPEN_AI_API_KEY_PROD",
} as const;

// 現在の実行モード（未設定なら "prod" 扱い）
const MODE = getScriptPropertyValue(SCRIPT_PROPERTIES.MODE) || "prod";
const isDev = MODE === "dev";

// OpenAI
export const OPEN_AI_API_KEY = getScriptPropertyValue(
  isDev
    ? SCRIPT_PROPERTIES.OPEN_AI_API_KEY
    : SCRIPT_PROPERTIES.OPEN_AI_API_KEY_PROD,
);

export const OPEN_AI_MODEL =
  getScriptPropertyValue(SCRIPT_PROPERTIES.OPEN_AI_MODEL) || "gpt-4o";

// Cloud Vision
export const CLOUD_VISION_API_KEY = getScriptPropertyValue(
  isDev
    ? SCRIPT_PROPERTIES.CLOUD_VISION_API_KEY
    : SCRIPT_PROPERTIES.CLOUD_VISION_API_KEY_PROD,
);

// フォルダID
export const OCR_FOLDER_ID = getScriptPropertyValue(
  isDev
    ? SCRIPT_PROPERTIES.OCR_FOLDER_ID
    : SCRIPT_PROPERTIES.OCR_FOLDER_ID_PROD,
);

export const DONE_OCR_FOLDER_ID = getScriptPropertyValue(
  isDev
    ? SCRIPT_PROPERTIES.DONE_OCR_FOLDER_ID
    : SCRIPT_PROPERTIES.DONE_OCR_FOLDER_ID_PROD,
);

export const ERROR_OCR_FOLDER_ID = getScriptPropertyValue(
  isDev
    ? SCRIPT_PROPERTIES.ERROR_OCR_FOLDER_ID
    : SCRIPT_PROPERTIES.ERROR_OCR_FOLDER_ID_PROD,
);
