import { getScriptPropertyValue } from "../../common/src/spreadsheet";

export const SCRIPT_PROPERTIES = {
  OCR_FOLDER_ID: "OCR_FOLDER_ID",
  CLOUD_VISION_API_KEY: "CLOUD_VISION_API_KEY",
  DONE_OCR_FOLDER_ID: "DONE_OCR_FOLDER_ID",
  ERROR_OCR_FOLDER_ID: "ERROR_OCR_FOLDER_ID",
  OPEN_AI_API_KEY: "OPEN_AI_API_KEY",
  OPEN_AI_MODEL: "OPEN_AI_MODEL",
  OCR_FOLDER_ID_PROD: "OCR_FOLDER_ID_PROD",
  ERROR_OCR_FOLDER_ID_PROD: "ERROR_OCR_FOLDER_ID_PROD",
  DONE_OCR_FOLDER_ID_PROD: "DONE_OCR_FOLDER_ID_PROD",
  OPEN_AI_API_KEY_PROD: "OPEN_AI_API_KEY_PROD",
} as const;

export const CLOUD_VISION_API_KEY = getScriptPropertyValue(
  SCRIPT_PROPERTIES.CLOUD_VISION_API_KEY,
);
export const OCR_FOLDER_ID = getScriptPropertyValue(
  SCRIPT_PROPERTIES.OCR_FOLDER_ID,
);

export const DONE_OCR_FOLDER_ID = getScriptPropertyValue(
  SCRIPT_PROPERTIES.DONE_OCR_FOLDER_ID,
);

export const ERROR_OCR_FOLDER_ID = getScriptPropertyValue(
  SCRIPT_PROPERTIES.ERROR_OCR_FOLDER_ID,
);

export const OPEN_AI_API_KEY = getScriptPropertyValue(
  SCRIPT_PROPERTIES.OPEN_AI_API_KEY,
);
export const OPEN_AI_MODEL = getScriptPropertyValue(
  SCRIPT_PROPERTIES.OPEN_AI_MODEL,
);

// 本番環境用の設定

export const OCR_FOLDER_ID_PROD = getScriptPropertyValue(
  SCRIPT_PROPERTIES.OCR_FOLDER_ID_PROD,
);
export const DONE_OCR_FOLDER_ID_PROD = getScriptPropertyValue(
  SCRIPT_PROPERTIES.DONE_OCR_FOLDER_ID_PROD,
);
export const ERROR_OCR_FOLDER_ID_PROD = getScriptPropertyValue(
  SCRIPT_PROPERTIES.ERROR_OCR_FOLDER_ID_PROD,
);
export const OPEN_AI_API_KEY_PROD = getScriptPropertyValue(
  SCRIPT_PROPERTIES.OPEN_AI_API_KEY_PROD,
);
